from __future__ import annotations

from typing import TYPE_CHECKING

from wexample_helpers.decorator.base_class import base_class

from .abstract_javascript_file_content_option import AbstractJavascriptFileContentOption

if TYPE_CHECKING:
    from pathlib import Path

    from wexample_filestate.const.types_state_items import TargetFileOrDirectoryType


@base_class
class BiomeOption(AbstractJavascriptFileContentOption):
    # Auto-generated files Biome should not touch. Formatting them is
    # pointless (they get regenerated by their tool) and Biome's output is
    # sometimes non-idempotent on huge codegen trees (TanStack
    # `routeTree.gen.ts`, GraphQL codegen schemas, Relay artifacts…) — which
    # would cause an infinite rectify loop.
    #
    # We DO NOT exclude bare `.d.ts` files (often hand-written in libraries),
    # nor `dist`/`build`/`node_modules` (those are already out of the
    # filestate scope via gitignore + tree config — no need to defend here).
    _GENERATED_FILE_SUFFIXES: tuple[str, ...] = (
        # `.gen.*` — TanStack Router, Drizzle, various codegen
        ".gen.ts",
        ".gen.tsx",
        ".gen.js",
        ".gen.jsx",
        ".gen.mjs",
        ".gen.cjs",
        # `.generated.*` — GraphQL codegen, Prisma client wrappers, MSW
        ".generated.ts",
        ".generated.tsx",
        ".generated.js",
        ".generated.jsx",
        ".generated.mjs",
        ".generated.cjs",
    )
    # Specific framework-generated files that don't carry a `.gen` suffix.
    _GENERATED_FILE_BASENAMES: frozenset[str] = frozenset(
        {
            "next-env.d.ts",  # regenerated by every `next build`
            "vite-env.d.ts",  # scaffolded by Vite, often re-emitted
        }
    )
    # Path fragments indicating a directory of generated artifacts.
    _GENERATED_PATH_FRAGMENTS: tuple[str, ...] = (
        "/__generated__/",  # Relay, Apollo, generic codegen convention
    )

    def get_description(self) -> str:
        return "Format and lint JavaScript/TypeScript code using Biome."

    def _apply_content_change(self, target: TargetFileOrDirectoryType) -> str:
        cache = self._get_or_build_batch_cache(target)
        path_key = str(target.get_path())
        if path_key in cache:
            return cache[path_key]
        return target.read_text()

    def _is_excluded_from_batch(self, item: TargetFileOrDirectoryType) -> bool:
        path = item.get_path()
        name = path.name
        if name in self._GENERATED_FILE_BASENAMES:
            return True
        if any(name.endswith(suffix) for suffix in self._GENERATED_FILE_SUFFIXES):
            return True
        path_str = str(path)
        if any(fragment in path_str for fragment in self._GENERATED_PATH_FRAGMENTS):
            return True
        return False

    # Biome is RAM-hungry on large generated files; chunking avoids OOM kills
    # (SIGKILL exit 137) when rectifying suites with 100+ TypeScript files.
    _BATCH_CHUNK_SIZE: int = 30

    def _run_batch_on_paths(
        self,
        reference_target: TargetFileOrDirectoryType,
        paths: list[Path],
    ) -> None:
        self._ensure_docker_container(reference_target)
        runner = self._get_or_create_runner(reference_target)
        for i in range(0, len(paths), self._BATCH_CHUNK_SIZE):
            chunk = paths[i : i + self._BATCH_CHUNK_SIZE]
            container_paths = [runner.rebase_path(p) for p in chunk]
            runner.execute(
                cmd=[
                    "biome",
                    "format",
                    "--write",
                    "--config-path=/tmp/biome.json",
                    *container_paths,
                ]
            )
